name: Coverity Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverity:
    name: Run Coverity Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake ninja-build gperf \
          python3-pip python3-setuptools python3-wheel git curl
        pip3 install west
        pip3 install -r scripts/requirements.txt

    - name: Initialize NCS workspace
      run: |
        west init -l .
        west update
        west zephyr-export

    - name: Download Coverity tool
      run: |
        mkdir coverity
        curl -L "https://scan.coverity.com/download/linux64" \
          --data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
          -o coverity_tool.tgz
        tar -xzf coverity_tool.tgz -C coverity --strip-components=1
        echo "$GITHUB_WORKSPACE/coverity/bin" >> $GITHUB_PATH
        
    - name: Build with Coverity capture
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/coverity/bin
        export APP_DIR=$GITHUB_WORKSPACE/applications/nrf_desktop
        mkdir -p build_54l10
        cd build_54l10

        cmake -GNinja -DBOARD=nrf54l15dk/nrf54l10/cpuapp \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DSYSBUILD=OFF \
              $APP_DIR

        cd ..
        cov-build --dir cov-int ninja -C build_54l10

   
    - name: Compress results
      run: tar czvf cov-int.tgz cov-int || true

    - name: Upload build log (for debug)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: coverity-build-log
        path: cov-int/build-log.txt

    - name: Submit analysis to Coverity
      run: |
        curl --form token=${{ secrets.COVERITY_TOKEN }} \
             --form email=savage.lin@gmail.com \
             --form file=@cov-int.tgz \
             --form version="ncs-$(date +'%Y%m%d')" \
             --form description="NCS project CI Coverity scan" \
             https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT_NAME }}
