name: Coverity Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverity:
    name: Run Coverity Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y build-essential curl

    - name: Download Coverity Tool
      run: |
        mkdir coverity
        curl -L "https://scan.coverity.com/download/linux64" \
          --data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
          -o coverity_tool.tgz
        tar -xzf coverity_tool.tgz -C coverity --strip-components=1

    - name: Build with Coverity
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/coverity/bin
        cov-build --dir cov-int make clean all

    - name: Submit analysis
      run: |
        tar czvf cov-int.tgz cov-int
        curl --form token=${{ secrets.COVERITY_TOKEN }} \
             --form email=you@example.com \
             --form file=@cov-int.tgz \
             --form version="$(date +'%Y%m%d')" \
             --form description="GitHub CI scan" \
             https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT_NAME }}
