name: Coverity Scan

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  coverity:
    runs-on: ubuntu-latest

    env:
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /home/runner/zephyr-sdk
      COVERITY_BIN: ${{ github.workspace }}/coverity/bin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gperf python3-pip device-tree-compiler
          pip3 install -U west
          west init -l .
          west update
          west zephyr-export

      - name: Setup Zephyr SDK
        uses: carlosperate/zephyr-toolchain-action@v1
        with:
          toolchain-version: 0.16.4

      - name: Extract Coverity
        run: |
          mkdir -p ${{ github.workspace }}/coverity
          tar -xf coverity_tool.tgz -C ${{ github.workspace }}/coverity --strip-components=1

      - name: Clean build cache
        run: rm -rf build_54l10 cov-int

      - name: Build with Coverity capture
        run: |
          export PATH=$PATH:$COVERITY_BIN
          cov-build --dir cov-int \
            west build -p -b nrf54l15dk/nrf54l10/cpuapp \
            -d build_54l10 \
            -s applications/nrf_desktop \
            -- \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DSYSBUILD=OFF \
            -DAPP_DIR=${{ github.workspace }}/applications/nrf_desktop

      - name: Archive Coverity intermediate directory
        uses: actions/upload-artifact@v4
        with:
          name: cov-int
          path: cov-int
