name: Coverity Static Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverity:
    runs-on: ubuntu-latest

    env:
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /home/runner/zephyr-sdk
      COVERITY_TOOL_PATH: ${{ github.workspace }}/coverity/bin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gperf python3-pip wget xz-utils
          pip3 install west
          west init -l .
          west update
          west zephyr-export

      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          tar -xf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          mv zephyr-sdk-0.16.4 $ZEPHYR_SDK_INSTALL_DIR
          $ZEPHYR_SDK_INSTALL_DIR/setup.sh -t all -h -c

      - name: Install Coverity CLI (you must upload or cache this directory)
        run: |
          ls $COVERITY_TOOL_PATH || echo "❗請確認已將 coverity/bin 放入 coverity 目錄下"

      - name: Build with Coverity Capture
        run: |
          export PATH=$PATH:$COVERITY_TOOL_PATH
          cov-build --dir cov-int \
            west build -p -b nrf54l15dk/nrf54l10/cpuapp \
            -d build_54l10 \
            -s applications/nrf_desktop \
            -- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSYSBUILD=OFF

      - name: Analyze with Coverity
        run: |
          export PATH=$PATH:$COVERITY_TOOL_PATH
          cov-analyze --dir cov-int --all --concurrency=4

      - name: Format Coverity Report
        run: |
          export PATH=$PATH:$COVERITY_TOOL_PATH
          cov-format-errors --dir cov-int --html-output cov-report --strip-path $(pwd)

      - name: Upload Coverity Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverity-report
          path: cov-report
