name: Coverity Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverity:
    name: Run Coverity Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache west & modules
      uses: actions/cache@v4
      with:
        path: |
          .west
          modules
          zephyr
          tools
        key: ${{ runner.os }}-west-${{ hashFiles('west.yml') }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build gperf \
          python3-pip python3-setuptools python3-wheel \
          build-essential curl git

    - name: Setup Zephyr & NCS
      run: |
        pip3 install west
        west init -l .
        west update
        west zephyr-export
        pip3 install -r scripts/requirements.txt

    - name: Download Coverity Tool
      run: |
        mkdir -p coverity
        curl -L "https://scan.coverity.com/download/linux64" \
          --data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
          -o coverity_tool.tgz
        tar -xzf coverity_tool.tgz -C coverity --strip-components=1
        echo "$GITHUB_WORKSPACE/coverity/bin" >> $GITHUB_PATH

    - name: List folders
      run: ls -R
      
    - name: Build with Coverity
      run: |
        cov-build --dir cov-int \
          west build -p -b nrf54l15dk/nrf54l10/cpuapp \
          -d build \
          -s applications/nrf_desktop \
          -- -DSYSBUILD=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Submit to Coverity Scan
      run: |
        tar czvf
